# Generated by Django 4.2 on 2023-04-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_title_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='titles/images/', verbose_name='Обложка'),
        ),
    ]
